# .github/workflows/gradle-build-pr.yml
# https://github.com/marketplace/actions/gradle-command
name: Gradle RC
on:
  schedule:
    - cron: 0 0 * * * # daily
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: rc
        arguments: checkAll
        build-root-directory: composite
